import { useState, useMemo } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { salaryApi } from '../api/client';
import { DataTable } from '../components/DataTable';
import {
  C, Card, Btn, Badge, Modal, Spinner,
  PageHeader, StatCard, fmtMoney, MONTHS, MONTHS_LG, CUR_MONTH, CUR_YEAR,
} from '../components/ui';

function printPayslip(emp, salary, month, year) {
  const w = window.open('', '_blank', 'width=680,height=900');
  w.document.write(`<!DOCTYPE html>
<html><head><title>Payslip — ${emp.name}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:Arial,sans-serif;color:#12182b;padding:40px;font-size:14px}
  .brand{font-size:22px;font-weight:800;color:#1e3a5f}
  .sub{color:#64748b;font-size:13px;margin-top:4px}
  .divider{border:none;border-top:2px solid #1e3a5f;margin:18px 0}
  table{width:100%;border-collapse:collapse}
  td{padding:7px 0;vertical-align:top}
  .label{color:#64748b;width:55%}
  .value{text-align:right;font-weight:500}
  .section{font-size:11px;font-weight:700;text-transform:uppercase;
    letter-spacing:.06em;color:#64748b;margin:18px 0 8px}
  .net{background:#1e3a5f;color:#fff;padding:14px 16px;border-radius:8px;
    display:flex;justify-content:space-between;align-items:center;margin-top:16px}
  .net-amount{font-size:22px;font-weight:800}
  .addition{color:#2a7a50}
  .deduction{color:#b83030}
  .footer{margin-top:40px;font-size:11px;color:#94a3b8;text-align:center}
</style></head><body>
<div style="display:flex;justify-content:space-between;align-items:flex-start">
  <div>
    <div class="brand">🪡 Classic Register</div>
    <div class="sub">Embroidery Business ERP</div>
  </div>
  <div style="text-align:right">
    <div style="font-size:18px;font-weight:700">PAYSLIP</div>
    <div class="sub">${MONTHS_LG[month-1]} ${year}</div>
  </div>
</div>
<hr class="divider">
<table>
  <tr><td class="label">Employee Name</td><td class="value">${emp.name}</td></tr>
  <tr><td class="label">Employee ID</td><td class="value">${emp.employee_id}</td></tr>
  <tr><td class="label">Designation</td><td class="value">${emp.role}</td></tr>
  <tr><td class="label">Pay Type</td><td class="value">${salary.salary_type}</td></tr>
  <tr><td class="label">Pay Period</td><td class="value">${MONTHS_LG[month-1]} ${year}</td></tr>
  <tr><td class="label">Working Days</td><td class="value">${salary.working_days} days</td></tr>
</table>
<div class="section">Attendance Summary</div>
<table>
  <tr><td class="label">Days Present</td><td class="value">${salary.present_days}</td></tr>
  <tr><td class="label">Half Days</td><td class="value">${salary.half_days}</td></tr>
  <tr><td class="label">Leave Days (paid)</td><td class="value">${salary.leave_days}</td></tr>
  <tr><td class="label">Absent Days</td><td class="value">${salary.absent_days}</td></tr>
  ${salary.total_hours > 0
    ? `<tr><td class="label">Hours Worked</td><td class="value">${salary.total_hours}h</td></tr>` : ''}
  ${salary.pieces_completed > 0
    ? `<tr><td class="label">Pieces Completed</td><td class="value">${salary.pieces_completed}</td></tr>` : ''}
  ${salary.total_ot_hours > 0
    ? `<tr><td class="label">Overtime Hours</td><td class="value">${salary.total_ot_hours}h</td></tr>` : ''}
</table>
<div class="section">Earnings &amp; Deductions</div>
<table>
  <tr><td class="label">Base Earned</td>
      <td class="value addition">${fmtMoney(salary.base_earned)}</td></tr>
  ${salary.overtime_pay > 0
    ? `<tr><td class="label">Overtime Pay</td>
       <td class="value addition">+ ${fmtMoney(salary.overtime_pay)}</td></tr>` : ''}
  ${salary.extratime_pay > 0
    ? `<tr><td class="label">Extra Time Pay</td>
       <td class="value addition">+ ${fmtMoney(salary.extratime_pay)}</td></tr>` : ''}
  <tr style="border-top:1px solid #e2e8f0">
    <td class="label" style="padding-top:10px"><strong>Gross Salary</strong></td>
    <td class="value" style="padding-top:10px"><strong>${fmtMoney(salary.gross_salary)}</strong></td>
  </tr>
  ${salary.leave_deduction > 0
    ? `<tr><td class="label">Deduction</td>
       <td class="value deduction">− ${fmtMoney(salary.leave_deduction)}</td></tr>` : ''}
</table>
<div class="net">
  <span>NET SALARY PAYABLE</span>
  <span class="net-amount">${fmtMoney(salary.net_salary)}</span>
</div>
<div class="footer">
  Generated by Classic Register ERP · ${new Date().toLocaleDateString('en-IN')}
</div>
</body></html>`);
  w.document.close();
  setTimeout(() => w.print(), 400);
}

function PayslipModal({ open, onClose, data, month, year, toast }) {
  const qc = useQueryClient();
  const logMut = useMutation({
    mutationFn: () => salaryApi.log({
      employee_id: data.employee.id,
      month, year, salary_data: data.salary,
    }),
    onSuccess: () => {
      qc.invalidateQueries(['salary-logs']);
      toast('Salary marked as paid ✓', 'success');
    },
    onError: err => toast(err.message, 'error'),
  });

  if (!open || !data) return null;
  const { employee: emp, salary } = data;

  const Row = ({ label, value, color, bold }) => (
    <div style={{
      display: 'flex', justifyContent: 'space-between',
      padding: '8px 0', borderBottom: `1px solid ${C.border}`,
    }}>
      <span style={{ fontSize: 14, color: C.muted }}>{label}</span>
      <span style={{ fontSize: 14, fontWeight: bold ? 700 : 500, color: color || C.text }}>
        {value}
      </span>
    </div>
  );

  return (
    <Modal open={open} onClose={onClose} title="Payslip Preview" width={500}>
      <div style={{
        background: C.primaryLight, padding: '14px 18px',
        borderRadius: 10, marginBottom: 20,
      }}>
        <div style={{ fontWeight: 700, fontSize: 16, color: C.primary }}>{emp.name}</div>
        <div style={{ fontSize: 13, color: C.muted }}>{emp.employee_id} · {emp.role}</div>
        <div style={{ fontSize: 13, color: C.muted, marginTop: 3 }}>
          {MONTHS_LG[month - 1]} {year} · <Badge status={salary.salary_type} />
        </div>
      </div>

      <div style={{ marginBottom: 16 }}>
        <div style={{
          fontSize: 11, fontWeight: 700, color: C.muted,
          textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6,
        }}>
          Attendance
        </div>
        <Row label="Days Present"      value={`${salary.present_days} days`} />
        <Row label="Half Days"         value={salary.half_days} />
        <Row label="Leave Days (paid)" value={salary.leave_days} />
        <Row label="Absent Days"       value={salary.absent_days} />
        {salary.total_hours    > 0 && <Row label="Hours Worked"      value={`${salary.total_hours}h`} />}
        {salary.pieces_completed > 0 && <Row label="Pieces Completed" value={salary.pieces_completed} />}
        {salary.total_ot_hours > 0 && <Row label="Overtime Hours"    value={`${salary.total_ot_hours}h`} />}
      </div>

      <div style={{ marginBottom: 6 }}>
        <div style={{
          fontSize: 11, fontWeight: 700, color: C.muted,
          textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6,
        }}>
          Earnings &amp; Deductions
        </div>
        <Row label="Base Earned"  value={fmtMoney(salary.base_earned)}  color={C.success} />
        {salary.overtime_pay > 0 &&
          <Row label="Overtime Pay" value={`+ ${fmtMoney(salary.overtime_pay)}`} color={C.success} />}
        {salary.extratime_pay > 0 &&
          <Row label="Extra Time Pay" value={`+ ${fmtMoney(salary.extratime_pay)}`} color={C.success} />}
        <Row label="Gross Salary" value={fmtMoney(salary.gross_salary)} bold />
        {salary.leave_deduction > 0 &&
          <Row label="Deduction" value={`− ${fmtMoney(salary.leave_deduction)}`} color={C.danger} />}
      </div>

      <div style={{
        background: C.primary, color: '#fff', borderRadius: 10,
        padding: '16px 20px', marginTop: 16,
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <span style={{ fontSize: 14, fontWeight: 600 }}>NET SALARY</span>
        <span style={{ fontSize: 24, fontWeight: 800 }}>{fmtMoney(salary.net_salary)}</span>
      </div>

      <div style={{ display: 'flex', gap: 10, marginTop: 18 }}>
        <Btn style={{ flex: 1 }} variant="outline"
          onClick={() => printPayslip(emp, salary, month, year)}>
          🖨 Print / Download
        </Btn>
        <Btn style={{ flex: 1 }} variant="success"
          onClick={() => logMut.mutate()}
          disabled={logMut.isPending}>
          {logMut.isPending ? 'Saving…' : '✅ Mark as Paid'}
        </Btn>
      </div>
    </Modal>
  );
}

export function Salary({ toast }) {
  const qc = useQueryClient();
  const [month,       setMonth]       = useState(CUR_MONTH);
  const [year,        setYear]        = useState(CUR_YEAR);
  const [payslipData, setPayslipData] = useState(null);

  const payrollQ = useQuery({
    queryKey: ['payroll', month, year],
    queryFn:  () => salaryApi.payroll(month, year),
    staleTime: 30_000,
  });

  const logsQ = useQuery({
    queryKey: ['salary-logs', month, year],
    queryFn:  () => salaryApi.logs({ month, year }),
    staleTime: 30_000,
  });

  const payroll  = payrollQ.data?.data?.payroll || [];
  const meta     = payrollQ.data?.data          || {};
  const paidLogs = logsQ.data?.data             || [];
  const paidIds  = new Set(paidLogs.map(l => l.employee_id));

  const columns = useMemo(() => [
    {
      id: 'employee', header: 'Employee',
      accessorFn: row => row.employee.name,
      cell: ({ row: { original: r } }) => (
        <div>
          <div style={{ fontWeight: 600 }}>{r.employee.name}</div>
          <div style={{ fontSize: 12, color: C.muted }}>
            {r.employee.employee_id} · {r.employee.role}
          </div>
        </div>
      ),
    },
    {
      id: 'pay_type', header: 'Pay Type',
      accessorFn: row => row.employee.salary_type,
      cell: ({ getValue }) => <Badge status={getValue()} />,
    },
    {
      id: 'present', header: 'Days / Hrs',
      cell: ({ row: { original: r } }) => {
        const s = r.salary;
        if (s.salary_type === 'hourly') return `${s.total_hours}h`;
        if (s.salary_type === 'piece')  return `${s.pieces_completed} pcs`;
        return `${s.present_days}d + ${s.half_days}hd`;
      },
    },
    {
      id: 'base', header: 'Base Earned',
      cell: ({ row: { original: r } }) => fmtMoney(r.salary.base_earned),
    },
    {
      id: 'ot', header: 'Overtime',
      cell: ({ row: { original: r } }) => (
        <span style={{ color: r.salary.overtime_pay > 0 ? C.success : C.muted }}>
          {r.salary.overtime_pay > 0 ? `+${fmtMoney(r.salary.overtime_pay)}` : '—'}
        </span>
      ),
    },
    {
      id: 'et', header: 'Extra Time',
      cell: ({ row: { original: r } }) => (
        <span style={{ color: r.salary.extratime_pay > 0 ? C.success : C.muted }}>
          {r.salary.extratime_pay > 0 ? `+${fmtMoney(r.salary.extratime_pay)}` : '—'}
        </span>
      ),
    },
    {
      id: 'ded', header: 'Deductions',
      cell: ({ row: { original: r } }) => (
        <span style={{ color: r.salary.leave_deduction > 0 ? C.danger : C.muted }}>
          {r.salary.leave_deduction > 0 ? `−${fmtMoney(r.salary.leave_deduction)}` : '—'}
        </span>
      ),
    },
    {
      id: 'net', header: 'Net Salary',
      cell: ({ row: { original: r } }) => (
        <span style={{ fontWeight: 700, fontSize: 15, color: C.primary }}>
          {fmtMoney(r.salary.net_salary)}
        </span>
      ),
    },
    {
      id: 'status', header: 'Status',
      cell: ({ row: { original: r } }) => (
        paidIds.has(r.employee.id)
          ? <Badge status="approved" label="Paid" />
          : <Badge status="pending"  label="Unpaid" />
      ),
    },
    {
      id: 'actions', header: 'Payslip',
      cell: ({ row: { original: r } }) => (
        <Btn size="sm" variant="outline" onClick={() => setPayslipData(r)}>
          View
        </Btn>
      ),
    },
  ], [paidIds]);

  const totalPaid   = payroll.filter(r => paidIds.has(r.employee.id)).length;
  const totalUnpaid = payroll.length - totalPaid;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <PageHeader
        title="Salary & Payroll"
        sub={`${MONTHS_LG[month - 1]} ${year} · ${payroll.length} employees`}
        action={
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <select
              value={month} onChange={e => setMonth(+e.target.value)}
              style={{ padding: '8px 10px', border: `1px solid ${C.border}`, borderRadius: 8, fontSize: 14 }}
            >
              {MONTHS.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
            </select>
            <input
              type="number" value={year} onChange={e => setYear(+e.target.value)}
              style={{ padding: '8px 10px', border: `1px solid ${C.border}`, borderRadius: 8, fontSize: 14, width: 80 }}
            />
          </div>
        }
      />

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12 }}>
        <StatCard label="Total Payroll" value={fmtMoney(meta.total_expense || 0)} color={C.primary} icon="💰" />
        <StatCard label="Employees"     value={payroll.length}                     color={C.purple}  icon="👥" />
        <StatCard label="Paid"          value={totalPaid}                          color={C.success} icon="✅" />
        <StatCard label="Unpaid"        value={totalUnpaid}                        color={C.warning} icon="⏳" />
        <StatCard label="Working Days"  value={`${meta.working_days || 0} days`}  color={C.muted}   icon="📅" />
      </div>

      <Card>
        <h3 style={{ margin: '0 0 14px', fontSize: 15, fontWeight: 600, color: C.text }}>
          Payroll — {MONTHS_LG[month - 1]} {year}
        </h3>
        {payrollQ.isLoading ? <Spinner /> : (
          <DataTable
            data={payroll}
            columns={columns}
            filterPlaceholder="Search employee…"
            pageSize={15}
          />
        )}
      </Card>

      <PayslipModal
        open={!!payslipData}
        onClose={() => setPayslipData(null)}
        data={payslipData}
        month={month}
        year={year}
        toast={toast}
      />
    </div>
  );
}